# Site settings
title: Stephen Suen
email: ssuen@mit.edu
description: 'Stephen Suen is a designer and developer who tells stories through data visualization and interactive media.'
baseurl: ''
url: 'http://stephensuen.com'

# Build settings
gems: [jekyll-paginate]
markdown: kramdown
permalink: /:categories/:title
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'pretty_print.xsl', 'vendor']
sass:
  sass_dir: assets/_sass
  style: compressed
paginate: 5
paginate_path: 'blog/page:num'
collections:
  work:
    output: true
    permalink: /work/:path/