# Site settings
title: Stephen Suen
email: ssuen@mit.edu
description: 'The online portfolio of Stephen Suen - design, storytelling, and the internets.'
baseurl: ''
url: 'http://stephensuen.com'

# Build settings
markdown: kramdown
permalink: /:categories/:title
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'pretty_print.xsl', 'vendor']
sass:
  sass_dir: assets/_sass
